### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by fjukevin** [MedMNIST/MedMNIST#18]
Hello, when i run "python -m medmnist save --flag=organmnist3d --folder=tmp/" , 
terminal show 
Saving organmnist3d train...
Using downloaded and verified file: /home/islab/.medmnist/organmnist3d.npz
Traceback (most recent call last):
  File "/home/islab/anaconda3/envs/covid/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/islab/anaconda3/envs/covid/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/islab/MedMNIST-main/medmnist/__main__.py", line 123, in <module>
    fire.Fire()
  File "/home/islab/anaconda3/envs/covid/lib/python3.6/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/islab/anaconda3/envs/covid/lib/python3.6/site-packages/fire/core.py", line 471, in _Fire
    target=component.__name__)
  File "/home/islab/anaconda3/envs/covid/lib/python3.6/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/islab/MedMNIST-main/medmnist/__main__.py", line 45, in save
    dataset.save(folder, postfix)
  File "/home/islab/MedMNIST-main/medmnist/dataset.py", line 169, in save
    assert postfix == "gif"
AssertionError

i dont know how to solve it , hope to help

Thank you in advance!

**Comment by ThreeSRR** [comment]
Hi @fjukevin ,
You can assign `--postfix=gif` when saving 3D datasets: 
`​python -m medmnist save --flag=xxxmnist3d --folder=tmp/ --postfix=gif`

**Comment by fjukevin** [comment]
thanks a lot
