### ISSUE TITLE
Encountering `BadZipFile` Bug When Loading `pathmnist.npz` Locally 

### ISSUE THREAD

**Issue by LZHMS** [MedMNIST/MedMNIST#39]
## My Problem
```
Traceback (most recent call last):
  File "/home/21009290012/Projects/DRLProjects/CNNLIME/train.py", line 303, in <module>
    main(data_flag, output_root, num_epochs, gpu_ids, batch_size, download, model_flag, resize, as_rgb, model_path, run)
  File "/home/21009290012/Projects/DRLProjects/CNNLIME/train.py", line 63, in main
    train_dataset = DataClass(split='train', transform=data_transform, download=False, as_rgb=as_rgb, root='dataset/')
  File "/home/21009290012/.conda/envs/DL_gpu/lib/python3.10/site-packages/medmnist/dataset.py", line 43, in __init__
    npz_file = np.load(os.path.join(self.root, "{}.npz".format(self.flag)))
  File "/home/21009290012/.conda/envs/DL_gpu/lib/python3.10/site-packages/numpy/lib/npyio.py", line 444, in load
    ret = NpzFile(fid, own_fid=own_fid, allow_pickle=allow_pickle,
  File "/home/21009290012/.conda/envs/DL_gpu/lib/python3.10/site-packages/numpy/lib/npyio.py", line 190, in __init__
    _zip = zipfile_factory(fid)
  File "/home/21009290012/.conda/envs/DL_gpu/lib/python3.10/site-packages/numpy/lib/npyio.py", line 103, in zipfile_factory
    return zipfile.ZipFile(file, *args, **kwargs)
  File "/home/21009290012/.conda/envs/DL_gpu/lib/python3.10/zipfile.py", line 1269, in __init__
    self._RealGetContents()
  File "/home/21009290012/.conda/envs/DL_gpu/lib/python3.10/zipfile.py", line 1336, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
```
### My Environment
+ Platform: Linux
+ Torch 1.13.0+cu116
+ Python: 3.10.12
### My Code
```
train_dataset = DataClass(split='train', transform=data_transform, download=False, as_rgb=as_rgb, root='dataset/')
```
### My Project Structure
```
CNNLIME
|---checkpoints
|---dataset
|        |---pathmnist.npz
|---model.py
|---train.py
```

**Comment by ThreeSRR** [comment]
Hi @LZHMS 

It seems that the npz file is broken. Maybe you could download it again from Zenodo.

**Comment by LZHMS** [comment]
Thanks for your help! It has been solved.
