### ISSUE TITLE
download by Command Line Tools | Something went wrong when downloading

### ISSUE THREAD

**Issue by katie312** [MedMNIST/MedMNIST#42]
hello, thank u so much for this amazing job!
I was trying to download one of the datasets by command line tool, I tried this command:
`python -m medmnist save --flag=organsmnist --folder=tmp/ --postfix=png 
--download=True --size=224`
but I've got this output which seems to be running to some wrong URL.
```Saving organsmnist train...
Traceback (most recent call last):
  File "/home/katie/miniconda3/envs/dreamnew/lib/python3.11/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/home/katie/miniconda3/envs/dreamnew/lib/python3.11/http/client.py", line 1286, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/katie/miniconda3/envs/dreamnew/lib/python3.11/http/client.py", line 1332, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/katie/miniconda3/envs/dreamnew/lib/python3.11/http/client.py", line 1281, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/katie/miniconda3/envs/dreamnew/lib/python3.11/http/client.py", line 1041, in _send_output
    self.send(msg)
  File "/home/katie/miniconda3/envs/dreamnew/lib/python3.11/http/client.py", line 979, in send
    self.connect()
  File "/home/katie/miniconda3/envs/dreamnew/lib/python3.11/http/client.py", line 1451, in connect
    super().connect()
  File "/home/katie/miniconda3/envs/dreamnew/lib/python3.11/http/client.py", line 945, in connect
    self.sock = self._create_connection(
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/katie/miniconda3/envs/dreamnew/lib/python3.11/socket.py", line 851, in create_connection
    raise exceptions[0]
  File "/home/katie/miniconda3/envs/dreamnew/lib/python3.11/socket.py", line 836, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/katie/miniconda3/envs/dreamnew/lib/python3.11/site-packages/medmnist/dataset.py", line 106, in download
    download_url(
  File "/home/katie/miniconda3/envs/dreamnew/lib/python3.11/site-packages/torchvision/datasets/utils.py", line 134, in download_url
    url = _get_redirect_url(url, max_hops=max_redirect_hops)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/katie/miniconda3/envs/dreamnew/lib/python3.11/site-packages/torchvision/datasets/utils.py", line 82, in _get_redirect_url
    with urllib.request.urlopen(urllib.request.Request(url, headers=headers)) as response:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/katie/miniconda3/envs/dreamnew/lib/python3.11/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/katie/miniconda3/envs/dreamnew/lib/python3.11/urllib/request.py", line 519, in open
    response = self._open(req, data)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/katie/miniconda3/envs/dreamnew/lib/python3.11/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/katie/miniconda3/envs/dreamnew/lib/python3.11/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/home/katie/miniconda3/envs/dreamnew/lib/python3.11/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/katie/miniconda3/envs/dreamnew/lib/python3.11/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 111] Connection refused>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/katie/miniconda3/envs/dreamnew/lib/python3.11/site-packages/medmnist/__main__.py", line 184, in <module>
    fire.Fire()
  File "/home/katie/miniconda3/envs/dreamnew/lib/python3.11/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/katie/miniconda3/envs/dreamnew/lib/python3.11/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
                                ^^^^^^^^^^^^^^^^^^^^
  File "/home/katie/miniconda3/envs/dreamnew/lib/python3.11/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/katie/miniconda3/envs/dreamnew/lib/python3.11/site-packages/medmnist/__main__.py", line 71, in save
    dataset = getattr(medalist, INFO[flag]["python_class"])(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/katie/miniconda3/envs/dreamnew/lib/python3.11/site-packages/medmnist/dataset.py", line 56, in __init__
    self.download()
  File "/home/katie/miniconda3/envs/dreamnew/lib/python3.11/site-packages/medmnist/dataset.py", line 113, in download
    raise RuntimeError(
RuntimeError: Something went wrong when downloading! Go to the homepage to download manually. https://github.com/MedMNIST/MedMNIST/
```

Am I trying a wrong command? Or something went wrong? I would really appreciate it if u could can help me with this.

**Comment by duducheng** [comment]
I've tested the downloading, which should work. I guess it's due to your network issues. You can try to download the files from Zenodo manually and put the files in your $root$.

Jiancheng

**Comment by katie312** [comment]
thx a lot! I will check my network env.
btw I am wondering can we download the 224*224 size of the imgs from Zenodo now? 
THX again for your work!

**Comment by katie312** [comment]
sorry for this stupid issue🥲, I have seen the 224*224 size dataset from Zenodo. 
THX anyway!

**Comment by duducheng** [comment]
I've just updated the downloading error message to make it more instructive: 

        except:
            raise RuntimeError(
                f"""
                Automatic download failed! Please download {self.flag}{self.size_flag}.npz manually.
                1. [Optional] Check your network connection: 
                    Go to {HOMEPAGE} and find the Zenodo repository
                2. Download the npz file from the Zenodo repository or its Zenodo data link: 
                    {self.info[f"url{self.size_flag}"]}
                3. [Optional] Verify the MD5: 
                    {self.info[f"MD5{self.size_flag}"]}
                4. Put the npz file under your MedMNIST root folder: 
                    {self.root}
                """
            )
